package com.euler;

import java.util.HashSet;
import java.util.Set;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class EvenFibonacciSum {

    public long execute(long max) {
        long n1 = 1, n2 = 2;
        Set<Long> evenFibNums = new HashSet<>();

        evenFibNums.add(n2);

        while (n1 + n2 < max) {
            long tmp = n1 + n2;
            if (tmp % 2 == 0) {
                evenFibNums.add(tmp);
            }
            n1 = n2; n2 = tmp;
        }

        return evenFibNums.stream().reduce(0L, Long::sum);
    }
}
